# Generated by Django 5.1.6 on 2025-02-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên chương trình'),
        ),
    ]
