# Generated by Django 5.0.11 on 2025-02-16 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Khuyến mãi', 'verbose_name_plural': 'Khuyến mãi'},
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='name',
        ),
        migrations.AddField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_discount_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Giảm giá tối đa'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_value',
            field=models.FloatField(default=0, verbose_name='Giá trị đơn hàng tối thiểu'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tên khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.IntegerField(default=0, verbose_name='Giới hạn sử dụng'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='Số lần đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phần trăm giảm giá'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.CreateModel(
            name='PromotionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateTimeField(auto_now_add=True)),
                ('discount_amount', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='app.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử sử dụng khuyến mãi',
                'verbose_name_plural': 'Lịch sử sử dụng khuyến mãi',
                'unique_together': {('promotion', 'order')},
            },
        ),
    ]
