# Generated by Django 5.0.11 on 2025-02-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_promotion_options_remove_promotion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_banners/', verbose_name='Ảnh bìa'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_cards/', verbose_name='Ảnh thẻ khuyến mãi'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Số tiền giảm'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Giảm theo phần trăm'), ('AMOUNT', 'Giảm theo số tiền')], default='PERCENT', max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='terms_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Điều kiện sử dụng'),
        ),
    ]
