# Generated by Django 5.1.4 on 2025-01-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='order',
        ),
    ]
