# Generated by Django 5.1.4 on 2025-01-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_oder_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_oder',
            new_name='date_orrder',
        ),
    ]
