# Generated by Django 5.1.6 on 2025-02-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_promotion_banner_image_promotion_card_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='Hình ảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nội dung giới thiệu',
                'verbose_name_plural': 'Nội dung giới thiệu',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Giờ làm việc')),
                ('map_image', models.ImageField(upload_to='contact/', verbose_name='Hình ảnh bản đồ')),
            ],
            options={
                'verbose_name': 'Thông tin liên hệ',
                'verbose_name_plural': 'Thông tin liên hệ',
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tiêu đề')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon class (Font Awesome)')),
            ],
            options={
                'verbose_name': 'Giá trị cốt lõi',
                'verbose_name_plural': 'Giá trị cốt lõi',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Hình ảnh')),
            ],
            options={
                'verbose_name': 'Danh mục sản phẩm',
                'verbose_name_plural': 'Danh mục sản phẩm',
            },
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_amount',
            field=models.FloatField(default=0, verbose_name='Số tiền giảm'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.FloatField(default=0, verbose_name='Phần trăm giảm'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('PERCENT', 'Giảm theo phần trăm'), ('AMOUNT', 'Giảm theo số tiền')], max_length=20, verbose_name='Loại giảm giá'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateTimeField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_discount_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Số tiền giảm tối đa'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateTimeField(verbose_name='Ngày bắt đầu'),
        ),
    ]
