# Generated by Django 5.1.4 on 2025-01-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orrder',
            new_name='date_order',
        ),
    ]
