# Generated by Django 5.0.11 on 2025-02-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_checkoutorder_delete_checkoutinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': 'Địa chỉ giao hàng', 'verbose_name_plural': 'Địa chỉ giao hàng'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(max_length=200, null=True, verbose_name='Quận/Huyện'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='full_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK', 'Chuyển khoản ngân hàng'), ('MOMO', 'Ví MoMo'), ('VNPAY', 'VNPay')], default='COD', max_length=20, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ward',
            field=models.CharField(max_length=200, null=True, verbose_name='Phường/Xã'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='Thành phố'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mobile',
            field=models.CharField(max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.DeleteModel(
            name='CheckoutOrder',
        ),
    ]
