# Generated by Django 5.0.11 on 2025-02-13 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_shippingaddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Thành phố')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phường/Xã')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ khách hàng',
                'verbose_name_plural': 'Hồ sơ khách hàng',
            },
        ),
    ]
